global using ItemizedThumbnailsList.Helpers;
global using ItemizedThumbnailsList.Models;
global using ItemizedThumbnailsList.ViewModels;
global using ItemizedThumbnailsList.Views.Pages;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Globalization;
global using System.Runtime.CompilerServices;
global using System.Text.Json;
